<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="1" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-31T01:55:52 IST" name="MySuite" finished-at="2024-12-31T01:55:52 IST" duration-ms="792">
    <groups>
    </groups>
    <test started-at="2024-12-31T01:55:52 IST" name="MyTests" finished-at="2024-12-31T01:55:52 IST" duration-ms="792">
      <class name="com.aryan.DatabaseConnectionTest">
        <test-method signature="testDatabaseConnection()[pri:0, instance:com.aryan.DatabaseConnectionTest@7671cb68]" started-at="2024-12-31T01:55:52 IST" name="testDatabaseConnection" finished-at="2024-12-31T01:55:52 IST" duration-ms="360" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDatabaseConnection -->
      </class> <!-- com.aryan.DatabaseConnectionTest -->
      <class name="com.aryan.SignupServletTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.aryan.SignupServletTest@1ef3efa8]" started-at="2024-12-31T01:55:52 IST" name="setUp" finished-at="2024-12-31T01:55:52 IST" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testDuplicateUserSignup()[pri:0, instance:com.aryan.SignupServletTest@1ef3efa8]" started-at="2024-12-31T01:55:52 IST" name="testDuplicateUserSignup" finished-at="2024-12-31T01:55:52 IST" duration-ms="52" status="FAIL">
          <exception class="org.mockito.exceptions.verification.WantedButNotInvoked">
            <message>
              <![CDATA[
Wanted but not invoked:
httpServletRequest.setAttribute(
    "errorMessage",
    "Username or email already exists."
);
-> at com.aryan.SignupServletTest.testDuplicateUserSignup(SignupServletTest.java:55)

However, there were exactly 4 interactions with this mock:
httpServletRequest.getParameter("username");
-> at com.aryan.SignupServlet.doPost(SignupServlet.java:18)

httpServletRequest.getParameter("email");
-> at com.aryan.SignupServlet.doPost(SignupServlet.java:19)

httpServletRequest.getParameter("password");
-> at com.aryan.SignupServlet.doPost(SignupServlet.java:20)

httpServletRequest.getContextPath();
-> at com.aryan.SignupServlet.doPost(SignupServlet.java:32)

]]>
            </message>
            <full-stacktrace>
              <![CDATA[Wanted but not invoked:
httpServletRequest.setAttribute(
    "errorMessage",
    "Username or email already exists."
);
-> at com.aryan.SignupServletTest.testDuplicateUserSignup(SignupServletTest.java:55)

However, there were exactly 4 interactions with this mock:
httpServletRequest.getParameter("username");
-> at com.aryan.SignupServlet.doPost(SignupServlet.java:18)

httpServletRequest.getParameter("email");
-> at com.aryan.SignupServlet.doPost(SignupServlet.java:19)

httpServletRequest.getParameter("password");
-> at com.aryan.SignupServlet.doPost(SignupServlet.java:20)

httpServletRequest.getContextPath();
-> at com.aryan.SignupServlet.doPost(SignupServlet.java:32)


at com.aryan.SignupServletTest.testDuplicateUserSignup(SignupServletTest.java:55)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- org.mockito.exceptions.verification.WantedButNotInvoked -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDuplicateUserSignup -->
        <test-method signature="testValidSignup()[pri:0, instance:com.aryan.SignupServletTest@1ef3efa8]" started-at="2024-12-31T01:55:52 IST" name="testValidSignup" finished-at="2024-12-31T01:55:52 IST" duration-ms="25" status="FAIL">
          <exception class="org.mockito.exceptions.verification.ArgumentsAreDifferent">
            <message>
              <![CDATA[Argument(s) are different! Wanted:
httpServletResponse.sendRedirect(
    "/login.jsp"
);
-> at com.aryan.SignupServletTest.testValidSignup(SignupServletTest.java:35)
Actual invocations have different arguments:
httpServletResponse.sendRedirect(
    "null/login.jsp"
);
-> at com.aryan.SignupServlet.doPost(SignupServlet.java:32)
]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.mockito.exceptions.verification.ArgumentsAreDifferent: Argument(s) are different! Wanted:
httpServletResponse.sendRedirect(
    "/login.jsp"
);
-> at com.aryan.SignupServletTest.testValidSignup(SignupServletTest.java:35)
Actual invocations have different arguments:
httpServletResponse.sendRedirect(
    "null/login.jsp"
);
-> at com.aryan.SignupServlet.doPost(SignupServlet.java:32)

at com.aryan.SignupServletTest.testValidSignup(SignupServletTest.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- org.mockito.exceptions.verification.ArgumentsAreDifferent -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testValidSignup -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.aryan.SignupServletTest@1ef3efa8]" started-at="2024-12-31T01:55:52 IST" name="setUp" finished-at="2024-12-31T01:55:52 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
      </class> <!-- com.aryan.SignupServletTest -->
      <class name="com.aryan.LoginServletTest">
        <test-method signature="testValidLogin()[pri:0, instance:com.aryan.LoginServletTest@59af0466]" started-at="2024-12-31T01:55:52 IST" name="testValidLogin" finished-at="2024-12-31T01:55:52 IST" duration-ms="318" status="FAIL">
          <exception class="org.mockito.exceptions.base.MockitoException">
            <message>
              <![CDATA[
Mockito cannot mock this class: interface java.sql.Connection.

If you're not sure why you're getting this error, please open an issue on GitHub.


Java               : 23
JVM vendor name    : Oracle Corporation
JVM vendor version : 23+37-2369
JVM name           : Java HotSpot(TM) 64-Bit Server VM
JVM version        : 23+37-2369
JVM info           : mixed mode, sharing
OS name            : Mac OS X
OS version         : 15.2


You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [interface java.sql.Connection, interface java.sql.Wrapper, interface java.lang.AutoCloseable]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: interface java.sql.Connection.

If you're not sure why you're getting this error, please open an issue on GitHub.


Java               : 23
JVM vendor name    : Oracle Corporation
JVM vendor version : 23+37-2369
JVM name           : Java HotSpot(TM) 64-Bit Server VM
JVM version        : 23+37-2369
JVM info           : mixed mode, sharing
OS name            : Mac OS X
OS version         : 15.2


You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [interface java.sql.Connection, interface java.sql.Wrapper, interface java.lang.AutoCloseable]
at com.aryan.LoginServletTest.testValidLogin(LoginServletTest.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
Caused by: org.mockito.exceptions.base.MockitoException: Could not modify all classes [interface java.sql.Connection, interface java.sql.Wrapper, interface java.lang.AutoCloseable]
at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:168)
at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:399)
at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:190)
at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:410)
... 31 more
Caused by: java.lang.IllegalStateException: 
Byte Buddy could not instrument all classes within the mock's type hierarchy

This problem should never occur for javac-compiled classes. This problem has been observed for classes that are:
 - Compiled by older versions of scalac
 - Classes that are part of the Android distribution
at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:285)
at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.mockClass(InlineBytecodeGenerator.java:218)
at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.lambda$mockClass$0(TypeCachingBytecodeGenerator.java:78)
at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:168)
at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:399)
at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:190)
at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:410)
at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:75)
at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createMockType(InlineDelegateByteBuddyMockMaker.java:396)
at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.doCreateMock(InlineDelegateByteBuddyMockMaker.java:355)
at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createMock(InlineDelegateByteBuddyMockMaker.java:334)
at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMock(InlineByteBuddyMockMaker.java:56)
at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:99)
at org.mockito.internal.MockitoCore.mock(MockitoCore.java:88)
at org.mockito.Mockito.mock(Mockito.java:2101)
at org.mockito.Mockito.mock(Mockito.java:2016)
... 31 more
Caused by: java.lang.IllegalArgumentException: Java 23 (67) is not supported by the current version of Byte Buddy which officially supports Java 21 (65) - update Byte Buddy or set net.bytebuddy.experimental as a VM property
at net.bytebuddy.utility.OpenedClassReader.of(OpenedClassReader.java:96)
at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:4011)
at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2224)
at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$UsingTypeWriter.make(DynamicType.java:4055)
at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3739)
at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.transform(InlineBytecodeGenerator.java:402)
at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:242)
at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:610)
at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:225)
at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:281)
... 46 more
]]>
            </full-stacktrace>
          </exception> <!-- org.mockito.exceptions.base.MockitoException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testValidLogin -->
      </class> <!-- com.aryan.LoginServletTest -->
    </test> <!-- MyTests -->
  </suite> <!-- MySuite -->
</testng-results>
